name: bird-lifespan
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - biopython
  - matplotlib
  - snakemake
  - dendropy
  - pip
  - pip:
      - gffutils
      - mygene
      - ete3
